name: Deploy Applications

on:
  workflow_dispatch: 
  workflow_call:

jobs:
  deploy-apiGateway:
    uses: ./.github/workflows/deploy-apiGateway.yaml
    secrets: inherit

  deploy-aiService:
    needs: deploy-apiGateway
    uses: ./.github/workflows/deploy-aiService.yaml
    secrets: inherit

  deploy-frontEnd:
    needs: deploy-apiGateway
    uses: ./.github/workflows/deploy-frontEnd.yaml
    secrets: inherit

