name: Deploy Application - Front End

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-frontEnd.yaml"
      - "frontEnd/**"
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_CLIENT_ID: ${{ secrets.AUTHSETTINGS_CLIENTSETTINGS_CLIENT_ID }}
      REACT_APP_CLIENT_SECRET: ${{ secrets.AUTHSETTINGS_CLIENTSETTINGS_CLIENT_SECRET }}
      REACT_APP_APIGATEWAY_URL: ${{ secrets.AZURE_APIGATEWAY_URL }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install
        working-directory: ./frontEnd

      - name: Build
        run: yarn build
        working-directory: ./frontEnd

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_FRONTEND }}
          action: "upload"
          app_location: "./frontEnd"
          api_location: ""
          output_location: "build"

